SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

PLAYER_RADIUS = 20
PLAYER_COLOR = "purple"
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.2

SHOT_RADIUS = 5
SHOT_COLOR = "yellow"
SHOT_SPEED = 300

ASTEROID_COLOR = "green"
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.5
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED = 100

LINE_WIDTH = 2
